name: Publish package
on:
  workflow_dispatch:

inputs:
  publish:
    description: 'Whether the package should be published to pub.dev (default: false)'
    required: false
    default: 'false'

jobs:
  publish-package:
    name: Publish package
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: spydon/flutter-publish@main
        with:
          publish: ${{ inputs.publish }}
